INSERT INTO row_address_dvf (
    line_hash,
    line_number,
    id,
    date_mutation,
    numero_disposition,
    nature_mutation,
    valeur_fonciere,
    adresse_numero,
    adresse_suffixe,
    adresse_code_voie,
    adresse_nom_voie,
    code_postal,
    code_commune,
    nom_commune,
    ancien_code_commune,
    ancien_nom_commune,
    code_departement,
    id_parcelle,
    ancien_id_parcelle,
    numero_volume,

    lot1_numero,
    lot1_surface_carrez,
    lot2_numero,
    lot2_surface_carrez,
    lot3_numero,
    lot3_surface_carrez,
    lot4_numero,
    lot4_surface_carrez,
    lot5_numero,
    lot5_surface_carrez,
    nombre_lots,

    code_type_local,
    type_local,
    surface_reelle_bati,
    nombre_pieces_principales,
    code_nature_culture,
    nature_culture,
    code_nature_culture_speciale,
    nature_culture_speciale,
    surface_terrain,
    longitude,
    latitude
)
VALUES (
    ?, ?, 
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?
);