INSERT INTO ban_address_final (
    id,
    id_fantoir,
    numero,
    rep,
    nom_voie,
    code_postal,
    code_insee,
    nom_commune,
    code_insee_ancienne_commune,
    nom_ancienne_commune,
    x,
    y,
    lon,
    lat,
    type_position,
    alias,
    nom_ld,
    libelle_acheminement,
    nom_afnor,
    source_position,
    source_nom_voie,
    certification_commune,
    cad_parcelles
) VALUES (
    :id,
    :idFantoir,
    :numero,
    :rep,
    :nomVoie,
    :codePostal,
    :codeInsee,
    :nomCommune,
    :codeInseeAncienneCommune,
    :nomAncienneCommune,
    :x,
    :y,
    :lon,
    :lat,
    :typePosition,
    :alias,
    :nomLd,
    :libelleAcheminement,
    :nomAfnor,
    :sourcePosition,
    :sourceNomVoie,
    :certificationCommune,
    :cadParcelles
)
ON CONFLICT(id) DO UPDATE SET
    id_fantoir = excluded.id_fantoir,
    numero = excluded.numero,
    rep = excluded.rep,
    nom_voie = excluded.nom_voie,
    code_postal = excluded.code_postal,
    code_insee = excluded.code_insee,
    nom_commune = excluded.nom_commune,
    code_insee_ancienne_commune = excluded.code_insee_ancienne_commune,
    nom_ancienne_commune = excluded.nom_ancienne_commune,
    x = excluded.x,
    y = excluded.y,
    lon = excluded.lon,
    lat = excluded.lat,
    type_position = excluded.type_position,
    alias = excluded.alias,
    nom_ld = excluded.nom_ld,
    libelle_acheminement = excluded.libelle_acheminement,
    nom_afnor = excluded.nom_afnor,
    source_position = excluded.source_position,
    source_nom_voie = excluded.source_nom_voie,
    certification_commune = excluded.certification_commune,
    cad_parcelles = excluded.cad_parcelles